// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.7
// source: ipc/cdp.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBrowserDebuggerPortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBrowserDebuggerPortRequest) Reset() {
	*x = GetBrowserDebuggerPortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_cdp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBrowserDebuggerPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrowserDebuggerPortRequest) ProtoMessage() {}

func (x *GetBrowserDebuggerPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_cdp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrowserDebuggerPortRequest.ProtoReflect.Descriptor instead.
func (*GetBrowserDebuggerPortRequest) Descriptor() ([]byte, []int) {
	return file_ipc_cdp_proto_rawDescGZIP(), []int{0}
}

type GetBrowserDebuggerPortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port uint32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *GetBrowserDebuggerPortResponse) Reset() {
	*x = GetBrowserDebuggerPortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_cdp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBrowserDebuggerPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrowserDebuggerPortResponse) ProtoMessage() {}

func (x *GetBrowserDebuggerPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_cdp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrowserDebuggerPortResponse.ProtoReflect.Descriptor instead.
func (*GetBrowserDebuggerPortResponse) Descriptor() ([]byte, []int) {
	return file_ipc_cdp_proto_rawDescGZIP(), []int{1}
}

func (x *GetBrowserDebuggerPortResponse) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type GetBrowserWsUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBrowserWsUrlRequest) Reset() {
	*x = GetBrowserWsUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_cdp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBrowserWsUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrowserWsUrlRequest) ProtoMessage() {}

func (x *GetBrowserWsUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_cdp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrowserWsUrlRequest.ProtoReflect.Descriptor instead.
func (*GetBrowserWsUrlRequest) Descriptor() ([]byte, []int) {
	return file_ipc_cdp_proto_rawDescGZIP(), []int{2}
}

type GetBrowserWsUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WsUrl string `protobuf:"bytes,1,opt,name=ws_url,json=wsUrl,proto3" json:"ws_url,omitempty"`
	Pid   uint32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *GetBrowserWsUrlResponse) Reset() {
	*x = GetBrowserWsUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_cdp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBrowserWsUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrowserWsUrlResponse) ProtoMessage() {}

func (x *GetBrowserWsUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_cdp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrowserWsUrlResponse.ProtoReflect.Descriptor instead.
func (*GetBrowserWsUrlResponse) Descriptor() ([]byte, []int) {
	return file_ipc_cdp_proto_rawDescGZIP(), []int{3}
}

func (x *GetBrowserWsUrlResponse) GetWsUrl() string {
	if x != nil {
		return x.WsUrl
	}
	return ""
}

func (x *GetBrowserWsUrlResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

var File_ipc_cdp_proto protoreflect.FileDescriptor

var file_ipc_cdp_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x70, 0x63, 0x2f, 0x63, 0x64, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x64, 0x70, 0x5f, 0x69, 0x70, 0x63, 0x22, 0x1f, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x42,
	0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x44, 0x65, 0x62, 0x75, 0x67, 0x67, 0x65, 0x72, 0x50, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x1e, 0x47, 0x65, 0x74,
	0x42, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x44, 0x65, 0x62, 0x75, 0x67, 0x67, 0x65, 0x72, 0x50,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x42, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x57, 0x73, 0x55,
	0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x42, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x57, 0x73, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x77, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x73, 0x55, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x32, 0xc9, 0x01,
	0x0a, 0x06, 0x43, 0x64, 0x70, 0x49, 0x70, 0x63, 0x12, 0x69, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x42,
	0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x44, 0x65, 0x62, 0x75, 0x67, 0x67, 0x65, 0x72, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x26, 0x2e, 0x63, 0x64, 0x70, 0x5f, 0x69, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x44, 0x65, 0x62, 0x75, 0x67, 0x67, 0x65, 0x72, 0x50,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x63, 0x64, 0x70,
	0x5f, 0x69, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x62, 0x75, 0x67, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x72, 0x6f, 0x77, 0x73, 0x65,
	0x72, 0x77, 0x73, 0x55, 0x72, 0x6c, 0x12, 0x1f, 0x2e, 0x63, 0x64, 0x70, 0x5f, 0x69, 0x70, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x57, 0x73, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x64, 0x70, 0x5f, 0x69, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x57, 0x73, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ipc_cdp_proto_rawDescOnce sync.Once
	file_ipc_cdp_proto_rawDescData = file_ipc_cdp_proto_rawDesc
)

func file_ipc_cdp_proto_rawDescGZIP() []byte {
	file_ipc_cdp_proto_rawDescOnce.Do(func() {
		file_ipc_cdp_proto_rawDescData = protoimpl.X.CompressGZIP(file_ipc_cdp_proto_rawDescData)
	})
	return file_ipc_cdp_proto_rawDescData
}

var file_ipc_cdp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ipc_cdp_proto_goTypes = []interface{}{
	(*GetBrowserDebuggerPortRequest)(nil),  // 0: cdp_ipc.GetBrowserDebuggerPortRequest
	(*GetBrowserDebuggerPortResponse)(nil), // 1: cdp_ipc.GetBrowserDebuggerPortResponse
	(*GetBrowserWsUrlRequest)(nil),         // 2: cdp_ipc.GetBrowserWsUrlRequest
	(*GetBrowserWsUrlResponse)(nil),        // 3: cdp_ipc.GetBrowserWsUrlResponse
}
var file_ipc_cdp_proto_depIdxs = []int32{
	0, // 0: cdp_ipc.CdpIpc.GetBrowserDebuggerPort:input_type -> cdp_ipc.GetBrowserDebuggerPortRequest
	2, // 1: cdp_ipc.CdpIpc.GetBrowserwsUrl:input_type -> cdp_ipc.GetBrowserWsUrlRequest
	1, // 2: cdp_ipc.CdpIpc.GetBrowserDebuggerPort:output_type -> cdp_ipc.GetBrowserDebuggerPortResponse
	3, // 3: cdp_ipc.CdpIpc.GetBrowserwsUrl:output_type -> cdp_ipc.GetBrowserWsUrlResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ipc_cdp_proto_init() }
func file_ipc_cdp_proto_init() {
	if File_ipc_cdp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ipc_cdp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBrowserDebuggerPortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_cdp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBrowserDebuggerPortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_cdp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBrowserWsUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_cdp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBrowserWsUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ipc_cdp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ipc_cdp_proto_goTypes,
		DependencyIndexes: file_ipc_cdp_proto_depIdxs,
		MessageInfos:      file_ipc_cdp_proto_msgTypes,
	}.Build()
	File_ipc_cdp_proto = out.File
	file_ipc_cdp_proto_rawDesc = nil
	file_ipc_cdp_proto_goTypes = nil
	file_ipc_cdp_proto_depIdxs = nil
}
