// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.7
// source: ipc/ocr.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaptchaImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width    uint32  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height   uint32  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Format   string  `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Image    []byte  `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Provider *string `protobuf:"bytes,5,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
}

func (x *CaptchaImage) Reset() {
	*x = CaptchaImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_ocr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptchaImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaImage) ProtoMessage() {}

func (x *CaptchaImage) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_ocr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaImage.ProtoReflect.Descriptor instead.
func (*CaptchaImage) Descriptor() ([]byte, []int) {
	return file_ipc_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *CaptchaImage) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CaptchaImage) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CaptchaImage) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CaptchaImage) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *CaptchaImage) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

type ResolvedCaptchaAnaswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *ResolvedCaptchaAnaswer) Reset() {
	*x = ResolvedCaptchaAnaswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_ocr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolvedCaptchaAnaswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedCaptchaAnaswer) ProtoMessage() {}

func (x *ResolvedCaptchaAnaswer) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_ocr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedCaptchaAnaswer.ProtoReflect.Descriptor instead.
func (*ResolvedCaptchaAnaswer) Descriptor() ([]byte, []int) {
	return file_ipc_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *ResolvedCaptchaAnaswer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_ipc_ocr_proto protoreflect.FileDescriptor

var file_ipc_ocr_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x70, 0x63, 0x2f, 0x6f, 0x63, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6f, 0x63, 0x72, 0x5f, 0x69, 0x70, 0x63, 0x22, 0x98, 0x01, 0x0a, 0x0c, 0x43, 0x61, 0x70,
	0x74, 0x63, 0x68, 0x61, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x22, 0x30, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x43,
	0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x41, 0x6e, 0x61, 0x73, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x32, 0x57, 0x0a, 0x06, 0x4f, 0x63, 0x72, 0x49, 0x70, 0x63, 0x12,
	0x4d, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68,
	0x61, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x15, 0x2e, 0x6f, 0x63, 0x72, 0x5f, 0x69, 0x70, 0x63,
	0x2e, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x1a, 0x1f, 0x2e,
	0x6f, 0x63, 0x72, 0x5f, 0x69, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64,
	0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x41, 0x6e, 0x61, 0x73, 0x77, 0x65, 0x72, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ipc_ocr_proto_rawDescOnce sync.Once
	file_ipc_ocr_proto_rawDescData = file_ipc_ocr_proto_rawDesc
)

func file_ipc_ocr_proto_rawDescGZIP() []byte {
	file_ipc_ocr_proto_rawDescOnce.Do(func() {
		file_ipc_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(file_ipc_ocr_proto_rawDescData)
	})
	return file_ipc_ocr_proto_rawDescData
}

var file_ipc_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ipc_ocr_proto_goTypes = []interface{}{
	(*CaptchaImage)(nil),           // 0: ocr_ipc.CaptchaImage
	(*ResolvedCaptchaAnaswer)(nil), // 1: ocr_ipc.ResolvedCaptchaAnaswer
}
var file_ipc_ocr_proto_depIdxs = []int32{
	0, // 0: ocr_ipc.OcrIpc.ResolveCaptchaImage:input_type -> ocr_ipc.CaptchaImage
	1, // 1: ocr_ipc.OcrIpc.ResolveCaptchaImage:output_type -> ocr_ipc.ResolvedCaptchaAnaswer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ipc_ocr_proto_init() }
func file_ipc_ocr_proto_init() {
	if File_ipc_ocr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ipc_ocr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptchaImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_ocr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolvedCaptchaAnaswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ipc_ocr_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ipc_ocr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ipc_ocr_proto_goTypes,
		DependencyIndexes: file_ipc_ocr_proto_depIdxs,
		MessageInfos:      file_ipc_ocr_proto_msgTypes,
	}.Build()
	File_ipc_ocr_proto = out.File
	file_ipc_ocr_proto_rawDesc = nil
	file_ipc_ocr_proto_goTypes = nil
	file_ipc_ocr_proto_depIdxs = nil
}
