// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: ipc/ocr.proto

package internal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OcrIpcClient is the client API for OcrIpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OcrIpcClient interface {
	ResolveCaptchaImage(ctx context.Context, in *CaptchaImage, opts ...grpc.CallOption) (*ResolvedCaptchaAnaswer, error)
}

type ocrIpcClient struct {
	cc grpc.ClientConnInterface
}

func NewOcrIpcClient(cc grpc.ClientConnInterface) OcrIpcClient {
	return &ocrIpcClient{cc}
}

func (c *ocrIpcClient) ResolveCaptchaImage(ctx context.Context, in *CaptchaImage, opts ...grpc.CallOption) (*ResolvedCaptchaAnaswer, error) {
	out := new(ResolvedCaptchaAnaswer)
	err := c.cc.Invoke(ctx, "/ocr_ipc.OcrIpc/ResolveCaptchaImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OcrIpcServer is the server API for OcrIpc service.
// All implementations must embed UnimplementedOcrIpcServer
// for forward compatibility
type OcrIpcServer interface {
	ResolveCaptchaImage(context.Context, *CaptchaImage) (*ResolvedCaptchaAnaswer, error)
	mustEmbedUnimplementedOcrIpcServer()
}

// UnimplementedOcrIpcServer must be embedded to have forward compatible implementations.
type UnimplementedOcrIpcServer struct {
}

func (UnimplementedOcrIpcServer) ResolveCaptchaImage(context.Context, *CaptchaImage) (*ResolvedCaptchaAnaswer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveCaptchaImage not implemented")
}
func (UnimplementedOcrIpcServer) mustEmbedUnimplementedOcrIpcServer() {}

// UnsafeOcrIpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OcrIpcServer will
// result in compilation errors.
type UnsafeOcrIpcServer interface {
	mustEmbedUnimplementedOcrIpcServer()
}

func RegisterOcrIpcServer(s grpc.ServiceRegistrar, srv OcrIpcServer) {
	s.RegisterService(&OcrIpc_ServiceDesc, srv)
}

func _OcrIpc_ResolveCaptchaImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptchaImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcrIpcServer).ResolveCaptchaImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ocr_ipc.OcrIpc/ResolveCaptchaImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcrIpcServer).ResolveCaptchaImage(ctx, req.(*CaptchaImage))
	}
	return interceptor(ctx, in, info, handler)
}

// OcrIpc_ServiceDesc is the grpc.ServiceDesc for OcrIpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OcrIpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocr_ipc.OcrIpc",
	HandlerType: (*OcrIpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveCaptchaImage",
			Handler:    _OcrIpc_ResolveCaptchaImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ipc/ocr.proto",
}
